### ISSUE TITLE
[RFE] Log all the steps taken

### ISSUE THREAD

**Issue by jorgemoralespou** [mfojtik/oinc#10]
It would be nice to have a log of what's been done, for later reference.

**Comment by mfojtik** [comment]
@jorgemoralespou `-v5` will show you what is being done :-)

**Comment by jorgemoralespou** [comment]
@mfojtik But what happens if I want to see what happened after I run oinc? Sometimes I do not know if things will go right and wrong. I guess this can be solve with a redirection or tee command.
